version: "3.2"
networks:
  app_network:
    driver: bridge
services:
  app:
    build:
      dockerfile: node.Dockerfile
      context: .
    image: jackson/app
    container_name: app
    links:
      - api
    networks:
      - app_network
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/
      - /app/node_modules
      - /app/dist
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'dbadmin'
      MYSQL_PASSWORD: 'dbpassword'
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: jackson/api2
    container_name: api
    links:
      - mysql
    networks:
      - app_network
    ports:
      - "8081:80"
    volumes:
      - ./api:/var/www/html/api
      - ./api/storage:/var/www/html/api/storage
    working_dir: "/var/www/html/api"
    tty: true
    environment:
      DB_HOST: 'mysql'
      DB_DATABASE: 'dbname'
      DB_USERNAME: 'dbadmin'
      DB_PASSWORD: 'dbpassword'
      APP_NAME: 'Laravel'
      APP_ENV: 'dev'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      APP_KEY: '234sfs3rt523fdg32567hv2345rhfc2e'
      DB_CONNECTION: 'mysql'
      TZ: 'America/Sao_Paulo'
volumes:
  db_data:
    driver: "local"
